# Generated by Django 5.2 on 2025-10-23 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('skintype', models.CharField(max_length=50)),
                ('skin_concern', models.JSONField(default=list)),
                ('eye_concern', models.JSONField(blank=True, null=True)),
                ('pregnant', models.BooleanField(default=False)),
                ('products_type', models.JSONField(blank=True, null=True)),
                ('routine', models.CharField(blank=True, max_length=200, null=True)),
                ('active_use', models.BooleanField(blank=True, null=True)),
                ('active_ingre', models.JSONField(blank=True, null=True)),
                ('advanced_active_use', models.CharField(blank=True, max_length=150, null=True)),
                ('no_products', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
