# Generated by Django 5.2 on 2025-10-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0004_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
