# Generated by Django 5.2 on 2025-11-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0005_userimage_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_brand', models.CharField(max_length=200)),
                ('product_cat', models.CharField(max_length=200)),
                ('product_main_ingre', models.JSONField()),
                ('product_link', models.URLField()),
                ('product_img', models.ImageField(upload_to='product/')),
            ],
        ),
    ]
