# Generated by Django 5.2 on 2025-11-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0006_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_target',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_link',
            field=models.URLField(max_length=500),
        ),
    ]
