# Generated by Django 5.2 on 2025-11-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0007_products_product_target_alter_products_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(null=True),
        ),
    ]
