# Generated by Django 5.2 on 2025-11-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0008_products_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
