# Generated by Django 5.2 on 2025-11-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0009_alter_products_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='skintypes',
            field=models.JSONField(null=True),
        ),
    ]
