# Generated by Django 5.2 on 2025-11-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0010_products_skintypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='eye_concern',
            field=models.JSONField(null=True),
        ),
    ]
