# Generated by Django 5.2 on 2025-11-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0012_userproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_des',
            field=models.TextField(null=True),
        ),
    ]
