# Generated by Django 5.2 on 2025-11-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0013_products_product_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_time',
            field=models.CharField(null=True),
        ),
    ]
