# Generated by Django 5.2 on 2026-01-20 01:52

from django.db import migrations
import json

def toArray(apps, schema_editor): 
    #get historical version of the Products model
    Products = apps.get_model("skincare", "Products")
    get_products = Products.objects.all()

    for row in get_products: 
        if isinstance(row.product_target, str): 
            row.product_target = json.loads(row.product_target) 
            print(row.product_target)
        else: 
            print(type(row.product_target))
        if isinstance(row.skintypes, str): 
            row.skintypes = json.loads(row.skintypes)
            print("\n")
            print("----------------------------")
            print(row.skintypes)
        else: 
            print(type(row.product_target))
        if isinstance(row.product_main_ingre, str):
            row.product_main_ingre = json.loads(row.product_main_ingre)
            print("\n")
            print("----------------------------")
            print(row.product_main_ingre)
        else: 
            print(type(row.product_target))
        row.save(update_fields=['skintypes', 'product_target', 'product_main_ingre'])
    
def reverse_toArray(apps, schema_editor): 
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0015_conversation_message'),
    ]

    operations = [
        migrations.RunPython(toArray, reverse_toArray)
    ]
