# Generated by Django 5.2 on 2026-01-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0016_auto_20260120_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_img',
            field=models.URLField(max_length=500),
        ),
    ]
